config/routes.rb
Rails.application.routes.draw do
  resources :estacionamientos
  resources :users
post '/main/index'
get '/main/index'
get '/main/history'
get '/main/settings'
get '/main/parking'
get '/main/parking_manager'
get "/sign-up/index"
get '/login/index'
post '/login/autenticate'

root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estacionamiento.rb
class Estacionamiento < ApplicationRecord

		validates :descripcion, :presence => { message: "El campo nombre es requerido" }
    validates :direccion, :presence => { message: "La dirección es un campo obligatorio" }
		mount_uploader :image, PictureUploader

end

app/models/user.rb
class User < ApplicationRecord
	validates :nombre, :presence => { message: "El campo nombre es requerido" },
                    :length => { :minimum => 2, :too_short => "El campo nombre debe ser mayor a 2" }
    validates :contrasenia, :presence => { message: "La contraseña es requerido" },
                    :length => { :minimum => 6, :too_short => "La contraseña debe ser mayor a 6" }

   
end

app/models/usuario.rb
class Usuario < ApplicationRecord
	validates :nombre, :presence => { message: "es requerido" },
                    :length => { :minimum => 5, :too_short => "debe ser mayor a 5" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/main_controller.rb
class MainController < ApplicationController
	layout 'main-app'
	def index

	end
	def history
	end
	def parking
	end
	def settings
		@user=User.find(session[:user]['id'])
	end
	def parking_manager
		@estacionamientos = Estacionamiento.all
		@estacionamiento=Estacionamiento.new
	end

end

app/controllers/estacionamientos_controller.rb
class EstacionamientosController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_estacionamiento, only: [:show, :edit, :update, :destroy]

  # GET /estacionamientos
  # GET /estacionamientos.json
  def index
    @estacionamientos = Estacionamiento.all
  end

  # GET /estacionamientos/1
  # GET /estacionamientos/1.json
  def show
  end

  # GET /estacionamientos/new
  def new
    @estacionamiento = Estacionamiento.new
  end

  # GET /estacionamientos/1/edit
  def edit
  end

  # POST /estacionamientos
  # POST /estacionamientos.json
  def create
    params[:estacionamiento][:id_proveedor]=session['user']['id']
    @estacionamiento = Estacionamiento.new(estacionamiento_params)

    respond_to do |format|
      if @estacionamiento.save
        format.html { redirect_to @estacionamiento, notice: 'Estacionamiento was successfully created.' }
        format.json { render :show, status: :created, location: @estacionamiento }
      else
        format.html { render :new }
        format.json { render json: @estacionamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estacionamientos/1
  # PATCH/PUT /estacionamientos/1.json
  def update
    respond_to do |format|
      if @estacionamiento.update(estacionamiento_params)
        format.html { redirect_to @estacionamiento, notice: 'Estacionamiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @estacionamiento }
      else
        format.html { render :edit }
        format.json { render json: @estacionamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estacionamientos/1
  # DELETE /estacionamientos/1.json
  def destroy
    @estacionamiento.destroy
    respond_to do |format|
      format.html { redirect_to estacionamientos_url, notice: 'Estacionamiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estacionamiento
      @estacionamiento = Estacionamiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estacionamiento_params
      params.require(:estacionamiento).permit(
        :descripcion,
        :tipo,
        :id_proveedor,
        :direccion,
        :latitud,
        :longitud,
         :altitud,
         :estado,
         :precio,
         :moneda,
         :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		    @user = User.new
		if params[:'sign-up']=='1'
			@show_modal=true
		end
	end 

end

app/controllers/login_controller.rb
class LoginController<ApplicationController
	def index
		@user=User.new
	end
	def autenticate
		@fields=[]
		@response={state:false,fields:{}}
		@ok=0
	if(params[:user]!=nil && params[:user].length>0)
			@ok=@ok+1
		else
			@fields.push('user')
        end
        if(params[:password]!=nil && params[:password].length>0)
			@ok=@ok+1
		else
			@fields.push('password')
        end
        	
          @response['fields']=@fields
		if(@ok==2)

			@user = User.where("usuario='#{params[:user]}' and contrasenia='#{params[:password]}'")
		
		if(@user!=nil and @user[0]!=nil)
			session[:user]=@user[0]
			@response['data']=@user[0].as_json

			@response['state']=true
		end
		end

        render json: JSON.pretty_generate(@response)
		
	end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
     params[:user][:estado]=1
     if(params[:user][:genero].nil?)
      params[:user][:genero]='F'

     end
     if(params[:user][:tipo_usuario].nil?)
      params[:user][:tipo_usuario]=2
      
     end

   @user = User.new(user_params)
    respond_to do |format|
      if @user.save
       format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
     
      params.require(:user).permit(
        :nombre, 
        :apellidos, 
        :edad, 
        :direccion, 
        :genero, 
        :usuario, 
        :contrasenia, 
        :estado, 
        :tipo_usuario)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estacionamientos_helper.rb
module EstacionamientosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/estacionamientos/_form.html.erb
<%= form_with(model: estacionamiento, format: :json,local: false,html:{id:"new-estacionamiento-form"}) do |form| %>
<div class=" alert alert-danger hide" id="estacionamiento-error_explanation">

 </div>
<ul class="stepper linear">
   <li class="step active">
      <div class="step-title waves-effect">Detalles</div>
      <div class="step-content">
         <div class="row">
           <div class="input-field col s12 m12 l6 xl6">
              <i class="material-icons prefix">insert_comment</i>
               <%= form.label :descripcion %>
               <%= form.text_field :descripcion, id: :estacionamiento_descripcion %>
           </div>
             <div class="input-field col s12 m12 l6 xl6">
              <i class="material-icons prefix">merge_type</i>

               <%= form.select :tipo,[["Privado","1"], [ "Público","2"]], id: :estacionamiento_tipo %>
                 <%= form.label :tipo %>
           </div>

             <div class="input-field col s12 m12 l6 xl6">
              <i class="material-icons prefix">merge_type</i>
             <%= form.label :direccion %>
           <%= form.text_field :direccion, id: :estacionamiento_direccion %>
           </div>
           <div class="input-field col s12 m12 l6 xl6">

        <div class="switch">
     <label>
       Inactivo
      <%= form.check_box :estado, id: :estacionamiento_estado,checked: true%>
       <span class="lever"></span>
       Activo
     </label>
   </div>


     </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">SIGUIENTE</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect">Geolocalización</div>
      <div class="step-content">
         <div class="row">
           <div class="input-field col s12 m12 l6 xl6">
             <i class="material-icons prefix">merge_type</i>
               <%= form.label :latitud %>
          <%= form.text_field :latitud, id: :estacionamiento_latitud %>
          </div>



          <div class="input-field col s12 m12 l6 xl6">
             <i class="material-icons prefix">merge_type</i>
                  <%= form.label :longitud %>
          <%= form.text_field :longitud, id: :estacionamiento_longitud %>
          </div>

             <div class="input-field col s12 m12 l6 xl6">

          <%= form.label :altitud %>
          <%= form.text_field :altitud, id: :estacionamiento_altitud %>
          </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">SIGUIENTE</button>
            <button class="waves-effect waves-dark btn-flat previous-step">ANTERIOR</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect">Otros</div>
      <div class="step-content">
         <div class="row">


        <div class="input-field col s12 m12 l6 xl6">
        <i class="material-icons prefix">merge_type</i>
       <%= form.label :precio %>
     <%= form.text_field :precio, id: :estacionamiento_precio,onkeyup: "number_only(event)" %>
     </div>

          <div class="input-field col s12 m12 l6 xl6">
        <i class="material-icons prefix">merge_type</i>
       <%= form.label :moneda %>
     <%= form.text_field :moneda, id: :estacionamiento_moneda %>
     </div>
     <div class="file-field input-field col s12 m12 l12 xl12">
<div class="btn">
  <span>File</span>
  <%=form.file_field :image, id: :estacionamiento_image%>
</div>
<div class="file-path-wrapper">
  <input class="file-path validate" type="text" placeholder="Seleccione imágenes">
</div>
</div>
         </div>
         <div class="step-actions">
             <%= form.submit 'GUARDAR',class: "hide",id: "new-parking-form-submit"%>
             <button type="button" onclick="form_submit('new-parking-form-submit')" class="waves-effect waves-dark btn white-text">GUARDAR</button>
         </div>
      </div>
   </li>
</ul>


<% end %>
<script>
   $('select').formSelect();

</script>

app/views/estacionamientos/edit.html.erb
<h1>Editing Estacionamiento</h1>

<%= render 'form', estacionamiento: @estacionamiento %>

<%= link_to 'Show', @estacionamiento %> |
<%= link_to 'Back', estacionamientos_path %>

app/views/estacionamientos/new.html.erb
<h1>New Estacionamiento</h1>

<%= render 'form', estacionamiento: @estacionamiento %>

<%= link_to 'Back', estacionamientos_path %>

app/views/estacionamientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @estacionamiento.descripcion %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @estacionamiento.tipo %>
</p>

<p>
  <strong>Id proveedor:</strong>
  <%= @estacionamiento.id_proveedor %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @estacionamiento.direccion %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @estacionamiento.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @estacionamiento.longitud %>
</p>

<p>
  <strong>Altitud:</strong>
  <%= @estacionamiento.altitud %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @estacionamiento.estado %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @estacionamiento.precio %>
</p>

<p>
  <strong>Moneda:</strong>
  <%= @estacionamiento.moneda %>
</p>

<%= link_to 'Edit', edit_estacionamiento_path(@estacionamiento) %> |
<%= link_to 'Back', estacionamientos_path %>

app/views/home/_new-user-form.html.erb
  <h4>Registrate</h4>
        <hr>
<%=form_with(model: new_user, local: true)  do |f| %>
  <% if @new_user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@new_user.errors.count, "error") %> prohibited
      this new_user from being saved:</h2>
    <ul>
    <% @new_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

 
         <div class="row">
           <div class="input-field col s12 m12 l6 xl6">
          <i class="material-icons prefix">account_circle</i>
          <!--input id="name" type="text" class="validate"-->
          <%=f.text_field :nombre %>
          <%=f.label :Nombres%>
        </div>

         </div>
  
<% end %>

app/views/home/index.html.erb
   <div class="navbar-fixed">
 <nav class="blue-grey darken-3">
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">WANT PARK <%=@show_modal%></a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right ">
       <li class="hide-on-med-and-down">
        	<%= link_to("login/index",{'class':'waves-effect waves-light btn indigo darken-4'}) do %>
 <i class="material-icons right">arrow_forward_ios</i>ACCEDER
<% end %>
        </li>
        <li class="hide-on-med-and-down">
        	
 <a class="waves-effect waves-light btn modal-trigger" href="#register-modal"><i class="material-icons right">person_add</i>REGISTRARSE</a>
        </li>
        <li class="hide-on-med-and-up">
          <a><i class="material-icons">search</i></a>
        </li>                
      
      </ul>
    </div>
  </nav>
</div>
  <ul class="sidenav" id="mobile-demo">
    <li>
      <%=link_to 'Acceder',controller:'login',action:'index'%>
    </li>
    <li>
        <%=link_to 'Registrarse',controller:'sign_up',action:'index'%>
    </li>
  </ul>

  <div home-search-bar class="hide-on-med-and-down">
  		<nav class="white">
    <div class="nav-wrapper">
      <form>
        <div class="input-field">
          <input id="search" type="search" required placeholder="Adónde vas?">
          <label class="label-icon" for="search"><i class="material-icons  black-text">search</i></label>
          <i class="material-icons">close</i>
        </div>
      </form>
    </div>
  </nav>
  </div>
<div class="parallax-container">
    <div class="parallax">
    	<img src="<%=image_path 'home-map.png'%>">

    </div>
</div> 
<div class="section white">
    <div class="row container">
       <div class="col s12 m12 l4 xl4 center">
        <i class="material-icons medium">search</i>
          <h5 class="header">Buscar</h5>
          <p class="grey-text text-darken-3 lighten-3">
            Encuentre el estacionamiento más barato y más cercano a su destino
          </p>
       </div>
        <div class="col s12 m12 l4 xl4 center">
        <i class="material-icons medium">payment</i>
          <h5 class="header">Pagar</h5>
          <p class="grey-text text-darken-3 lighten-3">
            Obtenga un lugar de estacionamiento garantizado por adelantado con su tarjeta de crédito.
          </p>
       </div>
        <div class="col s12 m12 l4 xl4 center">
        <i class="material-icons medium">directions_car</i>
          <h5 class="header">Parquear</h5>
          <p class="grey-text text-darken-3 lighten-3">
           Dirígete a tu destino y encontrarás un lugar esperándote.
          </p>
       </div>
    </div>
</div>
<div class="parallax-container">
    <div class="parallax"><img src="<%=image_path 'home-map.png'%>"></div>
</div>
 <div id="register-modal" class="modal">
    <div class="modal-content">
        <%=render 'users/form',user:@user%>
    </div>
    <div class="modal-footer">
      <a  class="pointer  waves-effect waves-green btn-flat" onclick="form_submit('submit_user_form')">
        Guardar
      </a>
      <a  class="pointer modal-close waves-effect waves-green btn-flat">
        Cancelar
      </a>
    </div>
  </div>
  <%if @show_modal%>
  <script>

    builtModal(true);
  </script>
      <%end%>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
   <meta name="theme-color" content="#546e7a">
   <meta name="mobile-web-app-capable" content="yes">
   <meta name="apple-mobile-web-app-capable" content="yes">

    <title>WantPark</title>
   <%= favicon_link_tag 'logo.png' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/layouts/main-app.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
   <meta name="theme-color" content="#546e7a">
   <meta name="mobile-web-app-capable" content="yes">
   <meta name="apple-mobile-web-app-capable" content="yes">

    <title>WantPark</title>
   <%= favicon_link_tag 'logo.png' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=render '/tags/index'%>
    <%= javascript_include_tag 'app', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>
      <ul id='dropdown_more_options' class='dropdown-content'>
    <li><a href="#!">
      <i class="material-icons">help</i> Ayuda
    </a>
  </li>

    <li class="divider" tabindex="-1"></li>
    <li>
      <a href="<%=url_for action:'index',controller:'home'%>"><i class="material-icons">exit_to_app</i> Salir</a>
    </li>
  </ul>

 <nav class="blue-grey darken-3">
  <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>


  <ul class="right" style="margin-right: 10px">
     <li>
<form onsubmit="find_parkings(event)">
  <input search-input type="text" placeholder="buscar..." class="browser-default" id="global-search" />
</form>
     </li>
      <li><a class="dropdown-trigger pointer"  data-target="dropdown_more_options">
        <i class="material-icons right">more_vert</i></a></li>
    </ul>
 </nav>

  <ul id="slide-out" class="sidenav sidenav-fixed">
    <li><div class="user-view">
      <div class="background">
        <img src="<%=image_path 'home-map.png'%>">
      </div>
      <a href="#user"><img class="circle" src="<%=image_path 'logo.png'%>"></a>
      <a href="#name"><span class="white-text name"><%=session[:user]['nombre']%> <%=session[:user]['apellidos']%></span></a>
      <a href="#email"><span class="white-text email"><%=session[:user]['usuario']%></span></a>
    </div>
  </li>
    <li>
      <a href="index" class="waves-effect">
        <i class="material-icons">home</i>Inicio
      </a>
      </li>

    <%if session[:user]['tipo_usuario']==1%>
      <li>
      <a href="parking" class="waves-effect">
        <i class="material-icons">directions_car</i>Estacionar
      </a>
    </li>
   <% else %>
     <li>
      <a href="parking_manager" class="waves-effect">
        <i class="material-icons">directions_car</i>Estacionamientos
      </a>
    </li>
    <% end %>

    <li>
      <a href="history" class="waves-effect">
        <i class="material-icons">history</i>Historial
      </a>
    </li>

    <li><div class="divider"></div></li>
    <li>
      <a class="subheader">Avanzado
      </a>
    </li>

    <li>
      <a href="settings" class="waves-effect">
        <i class="material-icons">settings</i>Configuración
      </a>
    </li>
  </ul>
<main>
    <%= yield %>
</main>
  </body>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5ViXXiO1AxSocJbj3uR4QaPcJbBlQN34&libraries=places"
    async defer></script>
  <script>
  window.globals={
    logo:'<%=image_path 'place'%>'
  };
        $('.dropdown-trigger').dropdown({hover:true,constrainWidth:false,coverTrigger:false});
         $('.sidenav').sidenav();
  </script>
  <!--script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap"></script-->

</html>

app/views/login/index.html.erb
<style>
body{
  background: #a7cbf8;
}
  body{
  background-image: url(<%=image_path 'home-map.png'%>);

       background-size: contain;
    background-repeat: no-repeat;
}
</style>
 <div class="row" style="    margin-top: 10%;">
    <div class="col s12 m12 l4 xl4  offset-l4 offset-xl4">
      <div class="card-panel">
  

    <form id="login-form" action="<%=url_for action:'autenticate',controller:'login'%>" accept-charset="UTF-8" method="post" data-remote="true" >
<input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="rfnFEP5ylWVwevZPoAiSiuBfoVKX/uT/gakpYK3MTjMV2VWf+7NkHmEbSHkj5OHeVUbyN/+TZYzpYC9B3Q4hXA==">
<input type="hidden" name="id" value="1">
     <div class="row">
      <div class="col s12 m12 l12 xl12 center">
          <img src="<%=image_path 'logo.png'%>" style="height: 100px">
      </div>
      <div class="col s12 m12 l12 xl12 center hide">
        <div class="alert alert-danger" id="login-form-message">
          <strong>Usuario y/o contraseña incorrecta, por favor intentelo otra vez!</strong>
        </div>
      </div>
        <div class="input-field col s12">
          <i class="material-icons prefix">account_circle</i>
          <input id="email" type="email" class="validate" name="user">
          <label for="email">Usuario</label>
           <span class="helper-text" data-error="email incorecto!" data-success=""></span>
        </div>
        <div class="input-field col s12">
          <i class="material-icons prefix">lock</i>
          <input id="password" type="password" class="validate" minlength="6" name="password">
          <label for="password">Contraseña</label>
           <span class="helper-text" data-error="La contraseña debe tener como mínimo 6 caracteres!" data-success=""></span>
       
      </div>
         <div class="col s12 m12 l12 xl12">
      <div class="switch">
    <label>
      <input type="checkbox" checked>
      <span class="lever"></span>
     Recordar mis datos
    </label>
  </div>
    </div>
     <div class="col s12 m12 l12 xl12 center" style="margin-top:10px">
      <button type="submit" class="waves-effect waves-light btn"><i class="material-icons left">send</i>Autenticar</button>
     </div>

   
      <div class="col s6 m6 l6 xl6" style="margin-top:20px">
      <%=link_to 'Olvidaste tus datos?'%>
      </div>
        <div class="col s6 m6 l6 xl6 right" style="margin-top:20px">
      <%=link_to 'Crear una cuenta',controller:"home",action:"index","sign-up":"1"%>
      </div>
     </div>
    </form>
      </div> 
    </div>
    </div>

app/views/main/index.html.erb
<div id='map' style='width:100%; height:700px;'></div>

  <div class="fixed-action-btn">
  <a class="btn-floating btn-large blue" onclick="getLocation()">
    <i class="large material-icons">my_location</i>
  </a>

</div>

app/views/main/parking.html.erb
<div class="card-panel">
	 <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <input id="icon_prefix" type="text" class="validate">
          <label for="icon_prefix">First Name</label>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">phone</i>
          <input id="icon_telephone" type="tel" class="validate">
          <label for="icon_telephone">Telephone</label>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/tags/_index.html.erb
<script type="riot/tag">
<%=render '/tags/parking'%>
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Edad</th>
      <th>Direccion</th>
      <th>Genero</th>
      <th>Usuario</th>
      <th>Contrasenia</th>
      <th>Estado</th>
      <th>Tipo usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.apellidos %></td>
        <td><%= user.edad %></td>
        <td><%= user.direccion %></td>
        <td><%= user.genero %></td>
        <td><%= user.usuario %></td>
        <td><%= user.contrasenia %></td>
        <td><%= user.estado %></td>
        <td><%= user.tipo_usuario %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @user.apellidos %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @user.edad %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @user.direccion %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @user.genero %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @user.usuario %>
</p>

<p>
  <strong>Contrasenia:</strong>
  <%= @user.contrasenia %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @user.estado %>
</p>

<p>
  <strong>Tipo usuario:</strong>
  <%= @user.tipo_usuario %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>